INDEX_FILE = "index.trained"
TOKEN_ID_FILE = "token_ids.pt"
INPUT_ID_FILE = "input_ids.pt"
RAW_FEATURE_KEY_SUFFIX = ".pt"
RAW_FEATURE_VALUE_SUFFIX = "_values.pt"
RAW_FEATURE_TOKEN_SUFFIX = "_tokens.pt"